AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs 
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FuncitonName: version
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /master
            Method: GET